### ISSUE TITLE
Exception: Cannot read properties of undefined (reading 'version')

### ISSUE THREAD

**Issue by geoidesic** [daidodo/format-imports-vscode#71] opened 2022-04-09 20:59 UTC
## Code snippet triggering the exception

I have no idea what's triggering it.

## All Logs

(Please open the output channel for "JS/TS Import/Export Sorter" and copy/paste ALL logs here)
er.. the what?   What is an "output channel" and where would I find it?

**Comment by daidodo** [comment] 2022-04-11 08:09
@geoidesic 

Could you share the logs when the issue happened? Thanks!
[Debug Mode](https://github.com/daidodo/format-imports-vscode/blob/master/CONTRIBUTING.md#debug-mode)

**Comment by gggdomi** [comment] 2022-04-11 10:13
Similar problem here : open any .ts file, save it "Something is wrong. Please open the logs and report an issue." pop-up appears.
Running `v7.4.17`

The logs:
```
[2022-04-11T12:07:10.083] [INFO] default - os: {
  arch: 'arm64',
  platform: 'darwin',
  type: 'Darwin',
  release: '21.4.0',
  totalmem: 34359738368,
  freemem: 2880716800,
  EOL: '\n'
}
[2022-04-11T12:07:10.084] [INFO] default - vscode: { version: '1.66.1' }
[2022-04-11T12:07:15.745] [INFO] vscode.resolveConfig - Resolving config for fileName: /Users/gui/Dev/loco/monoloco/src/back/src/features/cs/CMD_csLogin/controller.ts languageId: typescript
[2022-04-11T12:07:15.919] [ERROR] vscode.formatDocument - Found exception: TypeError: Cannot read properties of undefined (reading 'version')
    at /Users/gui/.vscode/extensions/dozerg.tsimportsorter-7.4.17/out/extension.js:2:1036324
    at Generator.next (<anonymous>)
    at /Users/gui/.vscode/extensions/dozerg.tsimportsorter-7.4.17/out/extension.js:2:1035632
    at new Promise (<anonymous>)
    at n (/Users/gui/.vscode/extensions/dozerg.tsimportsorter-7.4.17/out/extension.js:2:1035377)
    at /Users/gui/.vscode/extensions/dozerg.tsimportsorter-7.4.17/out/extension.js:2:1036068
    at /Users/gui/.vscode/extensions/dozerg.tsimportsorter-7.4.17/out/extension.js:2:1036632
    at Generator.next (<anonymous>)
    at /Users/gui/.vscode/extensions/dozerg.tsimportsorter-7.4.17/out/extension.js:2:1035632
    at new Promise (<anonymous>)
    at n (/Users/gui/.vscode/extensions/dozerg.tsimportsorter-7.4.17/out/extension.js:2:1035377)
    at t.enhanceWithEslint (/Users/gui/.vscode/extensions/dozerg.tsimportsorter-7.4.17/out/extension.js:2:1035989)
    at /Users/gui/.vscode/extensions/dozerg.tsimportsorter-7.4.17/out/extension.js:2:1042332
    at Generator.next (<anonymous>)
    at /Users/gui/.vscode/extensions/dozerg.tsimportsorter-7.4.17/out/extension.js:2:1041936
    at new Promise (<anonymous>)
    at n (/Users/gui/.vscode/extensions/dozerg.tsimportsorter-7.4.17/out/extension.js:2:1041681)
    at s (/Users/gui/.vscode/extensions/dozerg.tsimportsorter-7.4.17/out/extension.js:2:1042084)
    at /Users/gui/.vscode/extensions/dozerg.tsimportsorter-7.4.17/out/extension.js:2:1050401
    at Generator.next (<anonymous>)
    at /Users/gui/.vscode/extensions/dozerg.tsimportsorter-7.4.17/out/extension.js:2:1049919
    at new Promise (<anonymous>)
    at n (/Users/gui/.vscode/extensions/dozerg.tsimportsorter-7.4.17/out/extension.js:2:1049664)
    at l (/Users/gui/.vscode/extensions/dozerg.tsimportsorter-7.4.17/out/extension.js:2:1050232)
    at t.formatDocument (/Users/gui/.vscode/extensions/dozerg.tsimportsorter-7.4.17/out/extension.js:2:1837426)
    at /Users/gui/.vscode/extensions/dozerg.tsimportsorter-7.4.17/out/extension.js:2:1832324
    at p (/Users/gui/.vscode/extensions/dozerg.tsimportsorter-7.4.17/out/extension.js:2:1832388)
    at k._deliverEventAsync (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:31709)
    at k._deliverEventAsyncAndBlameBadListeners (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:30937)
    at k.$participateInSave (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:83:30638)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Thank you for all your work.

**Comment by daidodo** [comment] 2022-04-12 08:40
Please try v7.4.18.

I couldn't reproduce the issue but can guess what might be wrong.
Hope it will fix the issue.

**Comment by daidodo** [comment] 2022-04-12 16:49
Emm, I've released v7.4.19. That's not a fix but will log what caused the issue, hopefully.
Could you test it and share the logs in [Debug Mode](https://github.com/daidodo/format-imports-vscode/blob/master/CONTRIBUTING.md#debug-mode)?
Thanks!

**Comment by Athelian** [comment] 2022-04-13 00:48
Can confirm that my issue is fixed with v7.4.19! Thanks so much.

Here is my output with a successful format:
```
[2022-04-13T09:46:43.276] [INFO] vscode.formatDocument - Finished format
[2022-04-13T09:47:25.054] [INFO] vscode.resolveConfig - Resolving config for fileName: /home/ath/web-app/src/components/Form/DocumentsUpload/components/DocumentNavbarSecondRowContent/index.js languageId: javascript
[2022-04-13T09:47:25.062] [WARN] format-imports.loadESLintConfig - Failed to load ESLint config for fileName: /home/ath/web-app/src/components/Form/DocumentsUpload/components/DocumentNavbarSecondRowContent/index.js with error: Cannot read properties of undefined (reading 'version')
[2022-04-13T09:47:25.062] [INFO] format-imports.formatSource - Formatting /home/ath/web-app/src/components/Form/DocumentsUpload/components/DocumentNavbarSecondRowContent/index.js with enhanced config: {
  configurationFileName: 'import-sorter.json',
  autoFormat: 'off',
  formatExports: true,
  exclude: [ 'node_modules' ],
  excludeGlob: [],
  sortImportsBy: 'paths',
  groupRules: [
    '^react(-dom)?$',
    '^@angular/',
    '^vue$',
    '^node:',
    {},
    '^[@]',
    '^[.]'
  ],
  sortRules: { paths: [ '_', 'aA' ], names: [ '_', 'aA' ] },
  keepUnused: [],
  emptyLinesBetweenGroups: 1,
  emptyLinesAfterAllImports: 1,
  removeLastSlashInPath: false,
  removeLastIndexInPath: false,
  wrappingStyle: {
    maxBindingNamesPerLine: 1,
    maxDefaultAndBindingNamesPerLine: 2,
    maxExportNamesPerLine: 0,
    maxNamesPerWrappedLine: 1,
    ignoreComments: false
  },
  development: { enableDebug: false },
  insertFinalNewline: true,
  eol: 'LF',
  force: true,
  maxLineLength: 100,
  tabType: 'space',
  tabSize: 2,
  hasSemicolon: true,
  quoteMark: 'single',
  trailingComma: 'multiLine',
  bracketSpacing: true
}
[2022-04-13T09:47:25.095] [INFO] vscode.formatDocument - Finished format with no-op
```

**Comment by daidodo** [comment] 2022-04-13 08:28
@Athelian, thanks for the logs!

I'm glad it's working but the issue is still there:

```
format-imports.loadESLintConfig - Failed to load ESLint config for fileName: /home/ath/web-app/src/components/Form/DocumentsUpload/components/DocumentNavbarSecondRowContent/index.js with error: Cannot read properties of undefined (reading 'version')
```

Just to confirm you don't use ESLint in your project, right?
It'd be good if there is a demo project to root cause the issue.

**Comment by Athelian** [comment] 2022-04-14 07:17
@daidodo You're welcome.

Actually I am running ESLint in this project, is it okay? I don't know too much about ESLint things unfortunately...
So sorry for that and, sorry also but I cannot share the project code with you. I would if I could.

**Comment by daidodo** [comment] 2022-04-14 08:48
This plugin can [read ESLint configs and adjust the formatting](https://github.com/daidodo/format-imports-vscode#eslint-compatibility). With the issue your ESLint config will not be considered.

A demo project which can re-produce the issue is enough.
Thanks!

**Comment by gggdomi** [comment] 2022-04-20 11:38
@daidodo `v7.4.19` works for me too :)

In addition it now loads my prettier config, which failed in older versions 🎉 

If it helps :

- I still have the error `Failed to load ESLint config [...] Cannot read properties of undefined (reading 'version')` in logs
- but as I don't really use eslint, I don't really care here (in fact I'd be glad to ignore eslint altogether for imports - I use `"ignoreESLintRules": ".*"`). So this is perfect for me as it is.
- I tried to find a reproductible demo and found out that updating eslint from v6 to v8 seemed to solve the problem. Maybe you're using an old version of eslint too @Athelian and that's how you can reproduce?

**Comment by Athelian** [comment] 2022-04-20 11:54
@gggdomi Ohh yes confirmed I am on eslint v6 actually

**Comment by daidodo** [comment] 2022-04-22 07:13
Thanks for the callout! Is there anything else?

**Closed** 2022-05-02 20:41 UTC
Labels: bug, question
