### ISSUE TITLE
Save is slow

### ISSUE THREAD

**Issue by Zefling** [daidodo/format-imports-vscode#27] opened 2020-11-13 09:03 UTC
**Describe the bug**
Save is much slower when the extension is enabled

**To Reproduce**
Just use save

**Expected behavior**
A save that is done without too much slowing down.

**Actual behavior**
The save is slow, in some cases it is necessary to do 2 saves.

**OS (please complete the following information):**
 - OS: Windows
 - Version: 3.0.4

**VS Code (please complete the following information):**
 - Version: 1.51.1

**tsconfig.json (if any)**
```json
{
    "extends": "tslint:recommended",
    "linterOptions": {
      "exclude": [
        "**/*.notslint.ts"
      ]
    },
    "rules": {
      "array-type": false,
      "arrow-parens": false,
      "deprecation": false,
      "component-class-suffix": true,
      "contextual-lifecycle": true,
      "directive-class-suffix": false,
      "directive-selector": [
        true,
        "camelCase"
      ],
      "component-selector": [
        true,
        "element",
        "kebab-case"
      ],
      "import-blacklist": [
        true,
        "rxjs/Rx"
      ],
      "interface-name": false,
      "max-classes-per-file": false,
      "max-line-length": [
        true,
        120
      ],
      "member-access": false,
      "member-ordering": [
        true,
        {
          "order": [
            "static-field",
            "instance-field",
            "static-method",
            "instance-method"
          ]
        }
      ],
      "no-consecutive-blank-lines": false,
      "no-console": [
        true,
        "debug",
        "info",
        "time",
        "timeEnd",
        "trace"
      ],
      "no-empty": false,
      "no-inferrable-types": false,
      "no-non-null-assertion": true,
      "no-redundant-jsdoc": false,
      "no-switch-case-fall-through": true,
      "no-use-before-declare": true,
      "no-var-requires": false,
      "object-literal-key-quotes": false,
      "object-literal-sort-keys": false,
      "ordered-imports": false,
      "quotemark": [
        true,
        "single",
        "avoid-escape"
      ],
      "trailing-comma": false,
      "no-conflicting-lifecycle": false,
      "no-host-metadata-property": true,
      "no-input-rename": false,
      "no-inputs-metadata-property": true,
      "no-output-native": false,
      "no-output-on-prefix": false,
      "no-output-rename": false,
      "no-outputs-metadata-property": true,
      "template-banana-in-box": true,
      "template-no-negated-async": true,
      "use-lifecycle-interface": false,
      "use-pipe-transform-interface": true,
      "no-angle-bracket-type-assertion": false,
      "arrow-return-shorthand": false,
      "no-namespace": false,
      "interface-over-type-literal": false,
      "adjacent-overload-signatures": false,
      "one-variable-per-declaration": false,
      "ban": false,
      "ban-types": false,
      "no-string-literal": false,
      "prefer-for-of": false,
      "object-literal-shorthand": false,
      "space-before-function-paren": false,
      "only-arrow-functions": false,
      "semicolon": [
        true,
        "always"
      ],
      "whitespace": [
        true,
        "check-branch",
        "check-decl",
        "check-operator",
        "check-separator",
        "check-type"
      ],
      "import-destructuring-spacing": true,
      "framework-underscore-private": [
        true,
        "check-property",
        "check-constructor",
        "check-method"
      ],
      "framework-call-subject-next": true,
      "variable-name": [
        true,
        "check-format",
        "allow-leading-underscore",
        "ban-keywords"
      ]
    },
    "rulesDirectory": [
      "codelyzer",
      "@tools/tslint-rules"
    ]
  }
```

**.editorconfig (if any)**
```
    "tsImportSorter.configuration.maxBindingNamesPerLine": 0,
    "tsImportSorter.configuration.maxDefaultAndBindingNamesPerLine": 0,
    "tsImportSorter.configuration.maxNamesPerWrappedLine": 0,
    "tsImportSorter.configuration.configurationFileName": "C:\\Users\\XXXX\\AppData\\Roaming\\Code\\User\\import-sorter.json",
    "tsImportSorter.configuration.exclude": [
        "node_modules",
        "polyfills.ts",
        "polyfills.browser.ts"
    ]
```
```
{
  "maxLineLength": 120,
  "quoteMark": "simple",
  "tabSize": 4,
  "insertFinalNewline": false,
  "groupRules": [ 
	  {
		"regex": "^@angular/",
		"level": 10
	  },  
	  {
		"regex": "rxjs",
		"level": 11
	  },
	  {
		"regex": "^(?!(src|projects|lib)/)[a-z]",
		"level": 13
	  },
	  {
		"regex": "^@framework/",
		"level": 14
	  },
	  {
		"regex": "^[@]",
		"level": 15
	  },
	  {
		"regex": "^(src|lib|projects)/",
		"level": 20
	  },
	  {
		"regex": "^[.][.]",
		"level": 30
	  },
	  {
		"regex": "^(?!.*routing)[.]/",
		"level": 40
	  },
	  {
		"regex": "^[.]/",
		"level": 50
	  }
   ]
}
```

**Installed VS Code extensions**
```
cssho.vscode-svgviewer
deerawan.vscode-hasher
dozerg.tsimportsorter 
eamodio.gitlens
EditorConfig.EditorConfig
file-icons.file-icons
herrmannplatz.npm-dependency-links
jamesmaj.easy-icons
johnstoncode.svn-scm
LaurentTreguier.vscode-simple-icons
michelemelluso.gitignore
mike-co.import-sorter
ms-azuretools.vscode-docker
MS-CEINTL.vscode-language-pack-fr
ms-vscode-remote.remote-wsl
ms-vscode.vscode-typescript-tslint-plugin
msjsdiag.debugger-for-chrome
nepaul.editorconfiggenerator
obrejla.netbeans-light-theme
redhat.java
sasa.vscode-sass-format
Telerik.nativescript
traBpUkciP.vscode-npm-scripts
Tyriar.terminal-tabs
VisualStudioExptTeam.vscodeintellicode
vscjava.vscode-java-debug
vscjava.vscode-java-dependency
vscjava.vscode-java-pack
vscjava.vscode-java-test
vscjava.vscode-maven
xyz.local-history
```

**Comment by daidodo** [comment] 2020-11-25 22:26
@Zefling 

Thanks for your feedback!

Could you provide the code snippet or a link to the source file that causing the issue?
In my end (MacBook Pro) it takes ~130ms to format a 150-line TS file with 30 lines of imports.

You should be able to find out the exact time used when formatting a file in the Output channel for this extension:

<img width="704" alt="1" src="https://user-images.githubusercontent.com/8170176/100287734-1ed2bc00-2f6d-11eb-82b2-255e1cbe12f9.png">

Hope that helps!

**Comment by Zefling** [comment] 2020-11-26 11:11
I have this problem a workspace with a lot of projects. If I remove this extension, the slowdowns disappear.
![Sort2](https://user-images.githubusercontent.com/3032555/100344024-7a8a5d00-2fe0-11eb-8176-21c510bb3923.gif)
On a new workspace, not problem. It's strange.

**Comment by daidodo** [comment] 2020-11-26 12:27
Could you setup a shared workspace to reproduce the issue?

**Comment by Zefling** [comment] 2020-11-26 23:38
The workspace with project isn't possible because it's not a open source projects. :(

**Comment by daidodo** [comment] 2020-11-27 10:50
1. Is it only you having the issue or others too?
2. Have you tried to uninstall this extension and reinstall?
3. Could you reboot your computer or try on another one?

Looks like the first log (after resolving your configuration) took a long time to show. That could be because:
* A. The extension entry function took too long to start for some reason, or
* B. The configuration resolution took too long, or
* C. The output channel was stuck for some reason.

Reinstalling the extension might fix A and C if it's an env setup issue.
If not, it's most likely an I/O issue because this extension reads config from various sources, e.g package.json, tsconfig.json, Prettier's config, EditorConfig's config, etc. Reboot your computer or try on another one to see if it's a lock/disk issue.

**Comment by Zefling** [comment] 2020-11-30 09:16
With the new log: 
```
[2020-11-30T10:08:56.442] [INFO] formatDocument - Start formatting fileName: c:\xxxxxx\xxxx.ts
[2020-11-30T10:09:04.188] [INFO] formatDocument - Resolved config: {
```
I find this:
```
[2020-11-30 10:11:45.885] [renderer3] [warning] UNRESPONSIVE extension host, 'dozerg.tsimportsorter' took 100% of 3620.362ms, saved PROFILE here: 'c:\Users\CVEYSS~1\AppData\Local\Temp\exthost-a5edd4.cpuprofile' [{"id":"dozerg.tsimportsorter","total":3610140,"percentage":100},{"id":"eamodio.gitlens","total":235,"percentage":0},{"id":"gc","total":6140,"percentage":0},{"id":"self","total":975,"percentage":0},{"id":"vscode.merge-conflict","total":769,"percentage":0},{"id":"vscode.typescript-language-features","total":1771,"percentage":0}]
```

**Comment by daidodo** [comment] 2020-11-30 16:11
@Zefling 
Thanks for your helpful logs!

I've released a new revision (3.1.1) with more logs into config resolution. Could you try and share your new logs here?

**Comment by daidodo** [comment] 2020-12-15 14:21
Hi @Zefling,

From v4.1.0, you can switch on/off [Debug Mode](https://github.com/daidodo/tsimportsorter/blob/master/CONTRIBUTING.md#debug-mode) in User Settings. Maybe it can help you find useful logs if the issue appears again.

Thanks!

**Comment by Zefling** [comment] 2020-12-16 16:14
With the last version :

```
[2020-12-16T17:07:57.126] [INFO] vscode.resolveConfig - Start resolving configs for fileName: c:\xxxl\yyy.component.ts, languageId: typescript
[2020-12-16T17:07:57.128] [INFO] config.loadPretConfig - Prettier API version:  2.2.1
[2020-12-16T17:07:57.158] [INFO] config.loadESLintConfig - ESLint API version: 7.15.0
[2020-12-16T17:07:57.184] [WARN] config.loadESLintConfig - Failed loading ESLint config: No ESLint configuration found in c:\xxx.
[2020-12-16T17:08:06.711] [INFO] parser.formatSource - config: {
```

**Comment by daidodo** [comment] 2020-12-17 16:34
Thanks for your logs, @Zefling !

Looks like the issue is `tsconfig.json` loading.
I'm not sure about the root cause as your config worked fine in my laptop. But I'll keep watching it.

If you find more clues, please let me know and I'll appreciate it!

**Comment by JohnLouderback** [comment] 2021-01-16 21:22
For what it's worth, I also have a codebase that experiences this slowness.

**Comment by daidodo** [comment] 2021-01-16 21:27
@JohnLouderback 
Thanks for the feedback!

Is it possible that I can access the codebase? Or can you make a demo project to reproduce the issue?

**Comment by daidodo** [comment] 2021-04-06 21:28
@Zefling and @JohnLouderback - Are you still having the performance issue?
There is [another issue](https://github.com/daidodo/format-imports/issues/3) that might be related and I've fixed it, so I'll close this one.
Feel free to re-open it if you have more questions. Thanks!

**Closed by daidodo** 2021-04-06 21:28 UTC
Labels: bug, help wanted, question

**Comment by Zefling** [comment] 2021-04-06 21:52
Sorry, I'm no longer working on the problematic project. I haven't noticed the problem on other projects. It is possible that it is a problem of workspace.
